services:
  base-datos:
    image: postgres:15-alpine
    container_name: barberia_db_container
    restart: always
    environment:
      # Docker tomará los valores del archivo .env automáticamente
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - barberia-network  

  # --- SERVICIO DEL BACKEND (NUEVO) ---
  backend-java:
    build:
      context: ./backend-barber # Le dice a Docker que busque el Dockerfile aquí
      dockerfile: Dockerfile
    container_name: barberia_backend_container
    restart: always
    ports:
      - "8080:8080" # Expone el backend en el puerto 8080 de tu computadora
    environment:
      # Configuramos Spring Boot mediante variables de entorno para que lea la BD de Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://base-datos:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # Crea las tablas automáticamente en desarrollo
    depends_on:
      - base-datos # Le dice a Docker que no encienda el backend hasta que la BD esté lista
    networks:
      - barberia-network

volumes:
  postgres_data:

networks:
  barberia-network: # Red interna para que el backend y la BD se hablen por sus nombres
    driver: bridge